export SWARM_NET="test_net"
export DOCKER_IMAGE="nmmorais/hyparview:latest"
export IPS_FILE="config/IPS_FILE.txt"
export LATENCY_MAP="lats_file.txt"
export SWARM_VOL_DIR="/tmp/hyparview"
export SWARM_SUBNET="10.10.0.0/16"