export SWARM_NET="test_net"
export DOCKER_IMAGE="nmmorais/hyparview:latest"
export CONFIG_FILE="config/config_file.txt"
export LATENCY_MAP="lats_file.txt"
export SWARM_VOL="/tmp/hyparview"
export SWARM_SUBNET="10.10.0.0/16"